# Generated by Django 5.0.4 on 2024-05-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="local",
            name="due",
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
