# Generated by Django 5.0.4 on 2024-05-12 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_local_due"),
    ]

    operations = [
        migrations.DeleteModel(
            name="local",
        ),
    ]
