# Generated by Django 5.0.4 on 2024-05-13 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_delete_local"),
    ]

    operations = [
        migrations.CreateModel(
            name="categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=30)),
                ("descripcion", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="lugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referencia", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="comida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=300)),
                ("foto", models.ImageField(upload_to="")),
                ("precio", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.lugar"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nc", models.PositiveBigIntegerField(max_length=10)),
                ("p_nombre", models.CharField(max_length=50)),
                ("s_nombre", models.CharField(blank=True, max_length=50)),
                ("p_apellido", models.CharField(blank=True, max_length=50)),
                ("m_apellido", models.CharField(blank=True, max_length=50)),
                ("correo", models.EmailField(max_length=254)),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.rol"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reseña",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentaio", models.CharField(max_length=300)),
                ("calificacion", models.PositiveSmallIntegerField(max_length=1)),
                (
                    "comida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comida"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=300)),
                ("foto", models.ImageField(upload_to="")),
                ("hora_aper", models.TimeField()),
                ("hora_cier", models.TimeField()),
                ("categoria", models.ManyToManyField(to="core.categoria")),
                (
                    "lugar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.lugar"
                    ),
                ),
                (
                    "dueño",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usuario"
                    ),
                ),
            ],
        ),
    ]
