# Generated by Django 5.0.4 on 2024-05-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reseña",
            name="calificacion",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nc",
            field=models.PositiveBigIntegerField(),
        ),
    ]
